resources:
  - name: app
    type: gitRepo
    repoPath: manishas/app
    configuration:
      integrationName: manishas_github
      branches:
        only: master
    version:
      sha: master

  - name: npmSource
    type: file
    configuration:
      integrationName: art
    version:
      pattern: "npm-dev-local/"

  - name: bldInfo
    type: buildInfo
    version:
      buildName: native_pipeline
      buildNumber: 1

pipelines:
  - name: native_pipeline
    steps:
      - name: dockerBuild
        type: build
        configuration:
          affinityGroup: root
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173:8081/docker-local/demo
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - art
          resources:
            - app
            - npmSource

      - name: pushDockerImg
        type: push
        configuration:
          affinityGroup: root
        setup:
          push:
            targetRepo: docker-local
        requires:
          integrations:
            - art
        triggeredBy:
          steps:
            - dockerBuild

      - name: publishBldInfo
        type: publish
        configuration:
          affinityGroup: root
        requires:
          integrations:
            - art
        triggeredBy:
          steps:
            - pushDockerImg
        outputResources:
          - bldInfo

      - name: promoteBld
        type: promote
        configuration:
          affinityGroup: root
        setup:
          promote:
            targetRepo: demo
        requires:
          integrations:
            - art
        triggeredBy:
          resources:
            - bldInfo
                  
