resources:
  - name: app
    type: gitRepo
    repoPath: manishas/app
    configuration:
      integrationName: manishas_github
      branches:
        only: master
    initialVersion:
      sha: master
#
#  - name: azCluster
#    type: cluster
#    configuration:
#      integrationName: azure

#  - name: gcpCluster
#    type: cluster
#    configuration:
#      integrationName: gcp

  - name: gcpImg
    type: image
    imageName: imageRepo/imageName
    configuration:
      integrationName: gcp
    initialVersion:
      imageTag: latest

  - name: docImg
    type: image
    imageName: imageRepo/imageName
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest

pipelines:
  - name: ci_pipeline
    steps:
      - name: build
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - app
        execution:
          onExecute:
            - pushd $res_app_resourcePath
            - docker build -t app:latest .

      - name: test
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - build
        execution:
          onExecute:
            - docker run --name "test_app" app:latest bash -c "pwd"
            - docker rm -fv "test_app"

      - name: push
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        requires:
          integrations:
            - art
        triggeredBy:
          steps:
            - test
        execution:
          onExecute:
            - docker login -u $int_art_username -p $int_art_password $int_art_url
            - artIp=$(echo $int_art_url | awk -F[/:] '{print $4}')
            - artPort=$(echo $int_art_url | awk -F[/:] '{print $5}')
            - echo "$artIp:$artPort"
            - docker tag app:latest $artIp:$artPort/demo/app:$STEP_ID
            - docker push $artIp:$artPort/demo/app:$STEP_ID

      - name: job2
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - build
          resources:
            - docImg
        requires:
          resources:
            - gcpImg
        execution:
          onExecute:
            - echo "job2...."
            #- printenv
            - echo $res_gcpImg_int_masterName
            - echo $res_docImg_int_masterName
