resources:
  - name: app
    type: gitRepo
    repoPath: manishas/app
    configuration:
      integrationName: manishas_github
      branches:
        only: master
    version:
      sha: master

  - name: npmSource
    type: file
    configuration:
      integrationName: art
    version:
      pattern: "npm-dev-local/"

  - name: bldInfo
    type: buildInfo
    version:
      buildName: native_pipeline
      buildNumber: 1

pipelines:
  - name: native_pipeline
    steps:
      - name: dockerBuild
        type: build
        configuration:
          affinityGroup: root
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173:8081/docker-local/demo
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - art
          resources:
            - app
            - npmSource
