resources:
  - name: app
    type: gitRepo
    repoPath: manishas/app
    configuration:
      integrationName: manishas_github
      branches:
        only: master
    initialVersion:
      sha: master

  - name: app_img
    type: image
    imageName: manishas/app_img
    configuration:
     integrationName: art
    initialVersion:
     imageTag: latest

pipelines:
  - name: ci_pipeline
    steps:
      - name: build
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - app
        execution:
          onExecute:
            - pushd $res_app_resourcePath/gitRepo
            - echo $STEP_ID
            - docker build -t app:$STEP_ID .
            - write_output app_img "imageTag=$STEP_ID"
        outputResources:
          - app_img


      # - name: test
      #   type: bash
      #   setup:
      #     runtime:
      #       type: image
      #       image:
      #        custom:
      #          name: drydock/u16all
      #          tag: master
      #   triggeredBy:
      #     steps:
      #       - build
      #   execution:
      #     onExecute:
      #       - docker run --name "test_app" app:latest bash -c "pwd"
      #       - docker rm -fv "test_app"

      - name: push
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - app_img
        execution:
          onExecute:
            - echo $res_app_img_int_username
            - echo $res_app_img_int_password
            - echo $res_app_img_int_url
            - docker login -u $res_app_img_int_username -p $res_app_img_int_password $res_app_img_int_url
            #- artIp=$(echo $int_art_url | awk -F[/:] '{print $4}')
            #- artPort=$(echo $int_art_url | awk -F[/:] '{print $5}')
            #- echo "$artIp:$artPort"
            - docker tag app:$res_app_img_imagetag $res_app_img_int_username/app:$STEP_ID
            - docker push $res_app_img_int_username/app:$STEP_ID

      - name: job2
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master

        triggeredBy:
          steps:
            - build
        execution:
          onExecute:
            - echo "job2...."
